name: JavaScript

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-10.14

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, run lint
      run: |
        yarn install
        yarn run lint
      env:
        CI: true
